#!/bin/bash

echo "Running git pre-commit hook"
# Лучше использовать 80 символов
# почему? - так раньше становится видно когда код начинает быть плохим.
# 80 символов - хорошая длинна чтобы понимать когда стоит разделить на модули.
dart format --line-length 120 .
flutter analyze --no-fatal-infos

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && echo "ERROR: dart format and/or flutter analyze failed. Please fix the issues and re-commit." &&  exit 1
exit 0
