name: Build apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: |
          flutter pub get
          flutter build apk

      - if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-release.apk
